encoder: roberta
step_size: 100
epochs: 18
batch_size: 1
gradient_accumulation_steps: 3
mlm_probability: 0.15
momentum: 0.995
alpha: 0.4
max_seq_length: 512
numbed_model: CharLSTM_large
numbed_ckpt: data/ckpt/numbed-ckpt/CharLSTM_large.pt

optimizer: {lr: 1.5e-5, weight_decay: 0.02}
schedular: {T_0: 120, T_mult: 2, eta_min: 5e-6}
warm_up_steps: 3000

dataset_dir: [data/PretrainDataset/small]



