batch_size: 1
mlm_probability: 0.15
momentum: 0.995
alpha: 0.4
max_seq_length: 343

optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 5e-5, epochs: 18, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 12, cooldown_epochs: 0}







